/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RoleScoreService } from "../roleScore.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RoleScoreCreateInput } from "./RoleScoreCreateInput";
import { RoleScoreWhereInput } from "./RoleScoreWhereInput";
import { RoleScoreWhereUniqueInput } from "./RoleScoreWhereUniqueInput";
import { RoleScoreFindManyArgs } from "./RoleScoreFindManyArgs";
import { RoleScoreUpdateInput } from "./RoleScoreUpdateInput";
import { RoleScore } from "./RoleScore";
import { ScoreFindManyArgs } from "../../score/base/ScoreFindManyArgs";
import { Score } from "../../score/base/Score";
import { ScoreWhereUniqueInput } from "../../score/base/ScoreWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RoleScoreControllerBase {
  constructor(
    protected readonly service: RoleScoreService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "RoleScore",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RoleScore })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: RoleScoreCreateInput): Promise<RoleScore> {
    return await this.service.create({
      data: data,
      select: {
        backend: true,
        businessAnalyst: true,
        createdAt: true,
        dataScience: true,
        frontend: true,
        id: true,
        qa: true,
        saleEngineer: true,
        uiUx: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "RoleScore",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [RoleScore] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(RoleScoreFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<RoleScore[]> {
    const args = plainToClass(RoleScoreFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        backend: true,
        businessAnalyst: true,
        createdAt: true,
        dataScience: true,
        frontend: true,
        id: true,
        qa: true,
        saleEngineer: true,
        uiUx: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "RoleScore",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RoleScore })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: RoleScoreWhereUniqueInput
  ): Promise<RoleScore | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        backend: true,
        businessAnalyst: true,
        createdAt: true,
        dataScience: true,
        frontend: true,
        id: true,
        qa: true,
        saleEngineer: true,
        uiUx: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "RoleScore",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RoleScore })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: RoleScoreWhereUniqueInput,
    @common.Body() data: RoleScoreUpdateInput
  ): Promise<RoleScore | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          backend: true,
          businessAnalyst: true,
          createdAt: true,
          dataScience: true,
          frontend: true,
          id: true,
          qa: true,
          saleEngineer: true,
          uiUx: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "RoleScore",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RoleScore })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: RoleScoreWhereUniqueInput
  ): Promise<RoleScore | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          backend: true,
          businessAnalyst: true,
          createdAt: true,
          dataScience: true,
          frontend: true,
          id: true,
          qa: true,
          saleEngineer: true,
          uiUx: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Score",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/scores")
  @ApiNestedQuery(ScoreFindManyArgs)
  async findManyScores(
    @common.Req() request: Request,
    @common.Param() params: RoleScoreWhereUniqueInput
  ): Promise<Score[]> {
    const query = plainToClass(ScoreFindManyArgs, request.query);
    const results = await this.service.findScores(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,

        userId: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "RoleScore",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/scores")
  async connectScores(
    @common.Param() params: RoleScoreWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "RoleScore",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/scores")
  async updateScores(
    @common.Param() params: RoleScoreWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "RoleScore",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/scores")
  async disconnectScores(
    @common.Param() params: RoleScoreWhereUniqueInput,
    @common.Body() body: ScoreWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      scores: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
